### ISSUE TITLE
Not recognising property (solution) 

### ISSUE THREAD

**Issue by gugo2808** [vladduta/DigitRecognition#1]
def predict(self, input_img):
        if self.model is None:
            print("Model is not yet built")
            return

        if input_img is None:
            print("Input image not loaded properly")
            return None

        if len(input_img.shape) > 2:
            input_img = cv2.cvtColor(input_img, cv2.COLOR_BGR2GRAY)

        input_img = cv2.resize(input_img, (self.img_rows, self.img_cols))

        input_img = cv2.bitwise_not(input_img) #!!!!!!!!! very important line !!!!!!!!!! it switches colour, and program starts to work          #correctly

        cv2.imshow("input", input_img)

        cv2.waitKey(0)
        cv2.destroyAllWindows()

        input_img = input_img.astype('float32') / 255

        result = self.model.predict(np.reshape(input_img, (1, self.img_rows, self.img_cols, 1)))
        return np.argmax(result)

    def predict(self, input_img): have a look on the highlighted line, I think it could mega improve the recognition!

But anyway, thank you for the program!

**Comment by vladduta** [comment]
Thanks! I added that line and now the model makes better predictions since the input matches the MNIST format...
